/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import personProfile.profile;

/**
 *
 * @author pradyumnareddy
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    profile Profile;
    ImageIcon Ic;
    Image Ig;
    
    public CreateJPanel(profile Profile) {
        initComponents();
        this.Profile = Profile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeograpghic_data = new javax.swing.JLabel();
        lblteleno = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        lblEmailAdd = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblSocial_Security_numb = new javax.swing.JLabel();
        lblMedicRN = new javax.swing.JLabel();
        lblhpbn = new javax.swing.JLabel();
        lblban = new javax.swing.JLabel();
        lbnlicence = new javax.swing.JLabel();
        lblvehicleIdentifiers = new javax.swing.JLabel();
        lbldeviceID = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblipadds = new javax.swing.JLabel();
        lblUniqueidentity = new javax.swing.JLabel();
        lblBiometrc = new javax.swing.JLabel();
        lblfull_face_photo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographic_data = new javax.swing.JTextField();
        txtDate_of_birth = new javax.swing.JTextField();
        txtTelephoneno = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtSocial_Security_numb = new javax.swing.JTextField();
        txtMedic_RN = new javax.swing.JTextField();
        txthealthplan = new javax.swing.JTextField();
        txtBank_Acc_Numb = new javax.swing.JTextField();
        txtlicensenumb = new javax.swing.JTextField();
        txtVehicle_ID = new javax.swing.JTextField();
        txtdeviceidentity = new javax.swing.JTextField();
        txtLinkedIN = new javax.swing.JTextField();
        txtIPAdd = new javax.swing.JTextField();
        txtbiometric = new javax.swing.JTextField();
        txtFull_Face_photo = new javax.swing.JTextField();
        txtuniqueID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jButtonBrowseImage = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Create Profile");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblName.setText("Name");

        lblGeograpghic_data.setText("Geographic Data");

        lblteleno.setText("Telophone number");

        lblFAX.setText("FAX number");

        lblEmailAdd.setText("Email Address");

        lblDob.setText("Date of Birth");

        lblSocial_Security_numb.setText("Social Security Number");

        lblMedicRN.setText("Medical Record Number");

        lblhpbn.setText("Health Plan Beneficiary Number");

        lblban.setText("Bank Account Number");

        lbnlicence.setText("Licence Number");

        lblvehicleIdentifiers.setText("Vehicle Identifier");

        lbldeviceID.setText("Device Serial Number ");

        lblLinkedin.setText("LinkedIN");

        lblipadds.setText("IP Address");

        lblUniqueidentity.setText("Unique Identifier");

        lblBiometrc.setText("Biometric Identifier");

        lblfull_face_photo.setText("Full Face Picture");

        txtGeographic_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographic_dataActionPerformed(evt);
            }
        });

        btnSave.setText("SUBMIT");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblfull_face_photo)
                            .addComponent(lblBiometrc)
                            .addComponent(lblUniqueidentity)
                            .addComponent(lblipadds)
                            .addComponent(lblLinkedin)
                            .addComponent(lbldeviceID)
                            .addComponent(lblvehicleIdentifiers)
                            .addComponent(lbnlicence)
                            .addComponent(lblban)
                            .addComponent(lblhpbn)
                            .addComponent(lblMedicRN)
                            .addComponent(lblSocial_Security_numb)
                            .addComponent(lblDob)
                            .addComponent(lblEmailAdd)
                            .addComponent(lblFAX)
                            .addComponent(lblteleno)
                            .addComponent(lblGeograpghic_data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBrowseImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDate_of_birth, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTelephoneno, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmailID, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtfax, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSocial_Security_numb, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMedic_RN, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txthealthplan, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(txtBank_Acc_Numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtlicensenumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdeviceidentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFull_Face_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtuniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(167, 167, 167))
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(txtGeographic_data)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBank_Acc_Numb, txtDate_of_birth, txtEmailID, txtFull_Face_photo, txtGeographic_data, txtIPAdd, txtLinkedIN, txtMedic_RN, txtName, txtSocial_Security_numb, txtTelephoneno, txtVehicle_ID, txtbiometric, txtdeviceidentity, txtfax, txthealthplan, txtlicensenumb, txtuniqueID});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(17, 17, 17)
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeograpghic_data)
                    .addComponent(txtGeographic_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob)
                    .addComponent(txtDate_of_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblteleno)
                    .addComponent(txtTelephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAX)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAdd)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocial_Security_numb)
                    .addComponent(txtSocial_Security_numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicRN)
                    .addComponent(txtMedic_RN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhpbn)
                    .addComponent(txthealthplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblban)
                    .addComponent(txtBank_Acc_Numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnlicence)
                    .addComponent(txtlicensenumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehicleIdentifiers)
                    .addComponent(txtVehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeviceID)
                    .addComponent(txtdeviceidentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblipadds)
                    .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiometrc)
                    .addComponent(txtbiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfull_face_photo)
                    .addComponent(txtFull_Face_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUniqueidentity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButtonBrowseImage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeographic_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographic_dataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGeographic_dataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Profile.setName(txtName.getText());
        Profile.setGeographic_data(txtGeographic_data.getText());
        Profile.setDob(txtDate_of_birth.getText());
        Profile.setTelephone_number(Long.valueOf(txtTelephoneno.getText()));
        Profile.setFax_number(Long.valueOf(txtfax.getText()));
        Profile.setEmail_address(txtEmailID.getText());
        Profile.setSocial_Security_Number(Long.valueOf(txtSocial_Security_numb.getText()));
        Profile.setMedical_Record_Number(txtMedic_RN.getText());
        Profile.setHealth_plan_benificiary_number(Long.valueOf(txthealthplan.getText()));
        Profile.setBank_account_number(Long.valueOf(txtBank_Acc_Numb.getText()));
        Profile.setLicense_number(txtlicensenumb.getText());
        Profile.setVehicle_Identifier_licence_plate(txtVehicle_ID.getText());
        Profile.setDevice_Identifiers(txtdeviceidentity.getText());
        Profile.setLinkedIn(txtLinkedIN.getText());
        Profile.setInternet_protocol_address(txtIPAdd.getText());
        Profile.setPhoto(txtFull_Face_photo.getText());
        Profile.setUnique(Long.valueOf(txtuniqueID.getText()));
        
        if(validateIt()){
            JOptionPane.showMessageDialog(this, "Profile Information Saved");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();//
        FileNameExtensionFilter objFileExt = new FileNameExtensionFilter("qif", "png", "jpg", "jpeg", "IMAGES");
        int showOpenDialouge = browseImageFile.showOpenDialog(null);
        if (showOpenDialouge == JFileChooser.APPROVE_OPTION) {
        File selectedImageFile = browseImageFile.getSelectedFile();
        String selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null, selectedImagePath);
        txtFull_Face_photo.setText(selectedImagePath);
          Ic = new ImageIcon(selectedImagePath);
          Ig = Ic.getImage().getScaledInstance(jLabelImage.getWidth(),jLabelImage.getHeight(), Image.SCALE_SMOOTH);
          Profile.setImg(Ig);
      
        }
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed
    
    boolean validateIt(){
        boolean b = false;
        if(txtName.getText().isEmpty() || !Pattern.matches("^[a-zA-Z ]+$", txtName.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid Name");
            txtName.requestFocus();
        }
        
        if(txtGeographic_data.getText().equals("") || !Pattern.matches("^[0-9a-zA-Z ]+$", txtGeographic_data.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Geographical Data");
            txtGeographic_data.requestFocus();
        }
        if(txtTelephoneno.getText().equals("") || !Pattern.matches("^[0-9]{10}$",txtTelephoneno.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid Phone Number");
            txtTelephoneno.requestFocus();
        }
        if(txtBank_Acc_Numb.getText().equals("") || !Pattern.matches("^[0-9]+$",txtBank_Acc_Numb.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Bank Details");
            txtBank_Acc_Numb.requestFocus();
        }
        
        if(txtSocial_Security_numb.getText().equals("") || !Pattern.matches("^[0-9]{9}$",txtSocial_Security_numb.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Correct Social Security Number");
            txtSocial_Security_numb.requestFocus();
        }
              
        if(txtEmailID.getText().equals("") || !Pattern.matches("[a-zA-Z0-9.]+@[a-zA-Z.]+\\.[a-zA-Z]{2,}$",txtEmailID.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter valid Email ID");
            txtEmailID.requestFocus();
        }
        else
            b= true;
        return b;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel lblBiometrc;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblGeograpghic_data;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSocial_Security_numb;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueidentity;
    private javax.swing.JLabel lblban;
    private javax.swing.JLabel lbldeviceID;
    private javax.swing.JLabel lblfull_face_photo;
    private javax.swing.JLabel lblhpbn;
    private javax.swing.JLabel lblipadds;
    private javax.swing.JLabel lblteleno;
    private javax.swing.JLabel lblvehicleIdentifiers;
    private javax.swing.JLabel lbnlicence;
    private javax.swing.JTextField txtBank_Acc_Numb;
    private javax.swing.JTextField txtDate_of_birth;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFull_Face_photo;
    private javax.swing.JTextField txtGeographic_data;
    private javax.swing.JTextField txtIPAdd;
    private javax.swing.JTextField txtLinkedIN;
    private javax.swing.JTextField txtMedic_RN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocial_Security_numb;
    private javax.swing.JTextField txtTelephoneno;
    private javax.swing.JTextField txtVehicle_ID;
    private javax.swing.JTextField txtbiometric;
    private javax.swing.JTextField txtdeviceidentity;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txthealthplan;
    private javax.swing.JTextField txtlicensenumb;
    private javax.swing.JTextField txtuniqueID;
    // End of variables declaration//GEN-END:variables
}
