/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.Image;
import javax.swing.ImageIcon;
import personProfile.profile;

/**
 *
 * @author pradyumnareddy
 */
public class viewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
    
    profile Profile;
    
    public viewJPanel(profile Profile) {
        initComponents();
        
        this.Profile = Profile;
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsocial_security_number = new javax.swing.JLabel();
        txtlicensenumb = new javax.swing.JTextField();
        lblmrn = new javax.swing.JLabel();
        txtVehicleSerialnumb = new javax.swing.JTextField();
        lblhpbn = new javax.swing.JLabel();
        txtdeviceidentifier = new javax.swing.JTextField();
        lblbankacc = new javax.swing.JLabel();
        txtLinkedIN = new javax.swing.JTextField();
        lbnLicencenumb = new javax.swing.JLabel();
        lblvehicleIdentifiers = new javax.swing.JLabel();
        txtIPAdd = new javax.swing.JTextField();
        txtbiometricid = new javax.swing.JTextField();
        lblDevice_serial_numb = new javax.swing.JLabel();
        txtfullfacephoto = new javax.swing.JTextField();
        lblLinkedin = new javax.swing.JLabel();
        txtuniqueid = new javax.swing.JTextField();
        lblIPaddr = new javax.swing.JLabel();
        lblUniqueidentity = new javax.swing.JLabel();
        lblBiometrc = new javax.swing.JLabel();
        lblFullfacephoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographic_data = new javax.swing.JTextField();
        txtDate_of_birth = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txttelephoneno = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGeographic_data = new javax.swing.JLabel();
        txtFAX = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        lblteleno = new javax.swing.JLabel();
        txtSocial_Security_numb = new javax.swing.JTextField();
        lblfax = new javax.swing.JLabel();
        txtmedicRN = new javax.swing.JTextField();
        lblemailadds = new javax.swing.JLabel();
        txthealthplan = new javax.swing.JTextField();
        lblDate_of_birth = new javax.swing.JLabel();
        txtbankaccnumb = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();

        lblsocial_security_number.setText("Social Security Number");

        lblmrn.setText("Medical record Number");

        lblhpbn.setText("Health Plan Beneficiary Number");

        lblbankacc.setText("Bank Account Number");

        lbnLicencenumb.setText("Licence Number");

        lblvehicleIdentifiers.setText("Vehicle Number Identifier");

        lblDevice_serial_numb.setText("Device Serial Number ");

        lblLinkedin.setText("LinkedIN");

        lblIPaddr.setText("IP Address");

        lblUniqueidentity.setText("Unique Identifier");

        lblBiometrc.setText("Biometric Identifier");

        lblFullfacephoto.setText("Full Face Picture");

        txtGeographic_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographic_dataActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("View Profile");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblName.setText("Name");

        lblGeographic_data.setText("Geographic Data");

        lblteleno.setText("Telophone number");

        lblfax.setText("FAX number");

        lblemailadds.setText("Email Address");

        lblDate_of_birth.setText("Date of Birth");

        lblPhoto.setText("Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblFullfacephoto)
                    .addComponent(lblBiometrc)
                    .addComponent(lblUniqueidentity)
                    .addComponent(lblIPaddr)
                    .addComponent(lblLinkedin)
                    .addComponent(lblDevice_serial_numb)
                    .addComponent(lblvehicleIdentifiers)
                    .addComponent(lbnLicencenumb)
                    .addComponent(lblbankacc)
                    .addComponent(lblhpbn)
                    .addComponent(lblmrn)
                    .addComponent(lblsocial_security_number)
                    .addComponent(lblDate_of_birth)
                    .addComponent(lblemailadds)
                    .addComponent(lblfax)
                    .addComponent(lblteleno)
                    .addComponent(lblGeographic_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDate_of_birth, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttelephoneno, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEmailID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFAX, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSocial_Security_numb, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtmedicRN, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txthealthplan, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtbankaccnumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlicensenumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleSerialnumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdeviceidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbiometricid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfullfacephoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167))
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(txtGeographic_data)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDate_of_birth, txtEmailID, txtFAX, txtGeographic_data, txtIPAdd, txtLinkedIN, txtName, txtSocial_Security_numb, txtVehicleSerialnumb, txtbankaccnumb, txtbiometricid, txtdeviceidentifier, txtfullfacephoto, txthealthplan, txtlicensenumb, txtmedicRN, txttelephoneno, txtuniqueid});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeographic_data)
                            .addComponent(txtGeographic_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate_of_birth)
                            .addComponent(txtDate_of_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblteleno)
                    .addComponent(txttelephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfax)
                    .addComponent(txtFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemailadds)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsocial_security_number)
                    .addComponent(txtSocial_Security_numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmrn)
                    .addComponent(txtmedicRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhpbn)
                    .addComponent(txthealthplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankacc)
                    .addComponent(txtbankaccnumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnLicencenumb)
                    .addComponent(txtlicensenumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehicleIdentifiers)
                    .addComponent(txtVehicleSerialnumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevice_serial_numb)
                    .addComponent(txtdeviceidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPaddr)
                    .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiometrc)
                    .addComponent(txtbiometricid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullfacephoto)
                    .addComponent(txtfullfacephoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUniqueidentity))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeographic_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographic_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographic_dataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBiometrc;
    private javax.swing.JLabel lblDate_of_birth;
    private javax.swing.JLabel lblDevice_serial_numb;
    private javax.swing.JLabel lblFullfacephoto;
    private javax.swing.JLabel lblGeographic_data;
    private javax.swing.JLabel lblIPaddr;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueidentity;
    private javax.swing.JLabel lblbankacc;
    private javax.swing.JLabel lblemailadds;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblhpbn;
    private javax.swing.JLabel lblmrn;
    private javax.swing.JLabel lblsocial_security_number;
    private javax.swing.JLabel lblteleno;
    private javax.swing.JLabel lblvehicleIdentifiers;
    private javax.swing.JLabel lbnLicencenumb;
    private javax.swing.JTextField txtDate_of_birth;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtGeographic_data;
    private javax.swing.JTextField txtIPAdd;
    private javax.swing.JTextField txtLinkedIN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocial_Security_numb;
    private javax.swing.JTextField txtVehicleSerialnumb;
    private javax.swing.JTextField txtbankaccnumb;
    private javax.swing.JTextField txtbiometricid;
    private javax.swing.JTextField txtdeviceidentifier;
    private javax.swing.JTextField txtfullfacephoto;
    private javax.swing.JTextField txthealthplan;
    private javax.swing.JTextField txtlicensenumb;
    private javax.swing.JTextField txtmedicRN;
    private javax.swing.JTextField txttelephoneno;
    private javax.swing.JTextField txtuniqueid;
    // End of variables declaration//GEN-END:variables


    private void displayProfile() {
        
        txtName.setText(Profile.getName());
        txtGeographic_data.setText(Profile.getGeographic_data());
        txtDate_of_birth.setText(Profile.getDate_of_birth());
        txttelephoneno.setText(String.valueOf(Profile.getTelephone_number()));
        txtFAX.setText(String.valueOf(Profile.getFax_number()));
        txtEmailID.setText(Profile.getEmail_address());
        txtSocial_Security_numb.setText(String.valueOf(Profile.getSocial_Security_Number()));
        txtmedicRN.setText(Profile.getMedical_Record_Number());
        txthealthplan.setText(String.valueOf(Profile.getHealth_plan_benificiary_number()));
        txtbankaccnumb.setText(String.valueOf(Profile.getBank_account_number()));
        txtlicensenumb.setText(Profile.getLicense_number());
        txtVehicleSerialnumb.setText(Profile.getVehicle_Identifier_licence_plate());
        txtdeviceidentifier.setText(Profile.getDevice_Identifiers());
        txtLinkedIN.setText(Profile.getLinkedIn());
        txtIPAdd.setText(Profile.getInternet_protocol_address());
        txtfullfacephoto.setText(Profile.getPhoto());
        txtuniqueid.setText(String.valueOf(Profile.getUnique()));
        
        
        Image Img = Profile.getImg();
        if (Img != null){lblPhoto.setIcon(new ImageIcon(Img));}
    
    }
}
